<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'Gr 5 Carriage Bolt Assortment, 1/4 - 1/2 UNC',
                'arabic_title' => null,
                'description' => '<p>S/S Carriage Bolt Assortment</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051001.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '85572',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ],
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'Metric Carr Bolt Refill Asst, M8-M12',
                'arabic_title' => null,
                'description' => '<p>Metric Carr Bolt Refill Asst</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051002.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '185060',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ],
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'Gr 5 Carriage Bolt Refill Asst, 1/4 - 1/2 UNC',
                'arabic_title' => null,
                'description' => '<p>Gr 5 Carriage Bolt Refill Asst</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051003.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '185317',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ],
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'Gr 2 Carriage Bolt Refill Asst, 3/16 - 3/8 UNC',
                'arabic_title' => null,
                'description' => '<p>Gr 2 Carriage Bolt Refill Asst</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051004.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '185336',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ],
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'Gr 5 Carriage Bolt Refill Asst, 1/4-1/2 Long',
                'arabic_title' => null,
                'description' => '<p>Gr 5 Carriage Bolt Refill Asst</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051005.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '185377',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ],
            [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'product_title' => 'S/S Carriage Bolt Refill Asst, 1/4 - 1/2 UNC',
                'arabic_title' => null,
                'description' => '<p>S/S Carriage Bolt Refill Asst</p>',
                'additional_information' => null,
                'arabic_description' => null,
                'category' => '308',
                'subcategory' => null,
                'childsubcategory' => null,
                'language' => null,
                'color' => null,
                'price' => '50.00',
                'maximum_price' => null,
                'tags' => null,
                'sar_price' => null,
                'qar_price' => null,
                'bhr_price' => null,
                'omr_price' => null,
                'us_price' => null,
                'kwd_price' => null,
                'egp_price' => null,
                'jod_price' => null,
                'image' => 'uploads/products/20240523051006.jpg',
                'images' => null,
                'sku' => 'N/A',
                'status' => '1',
                'price2' => '0.00',
                'price3' => '0.00',
                'price4' => '0.00',
                'size' => null,
                'in_stock' => '1',
                'product_download_expiry' => '24',
                'zip' => null,
                'item_number' => '185572',
                'unspsc' => 'N/A',
                'manufacturer' => 'N/A',
                'brand' => null,
                'attributes' => null,
                'qty' => '1',
                'weight' => 'N/A',
            ]
        ];

        DB::table('products')->insert($products);
    }
}
